export const PLANETS = [
  {
    name: 'Mercury',
    radius: 0.25,
    orbitRadius: 5,
    orbitSpeed: 1.5,
    selfRotationSpeed: 0.5,
    color: 0x9c8d7b,
    diameter: '4,879 km',
    distanceFromSun: '57.9 million km',
    moons: 0,
    atmosphere: 'Virtually none — thin exosphere of oxygen, sodium, hydrogen and helium',
    funFact: 'A day on Mercury lasts 59 Earth days, but a year lasts only 88 Earth days.',
  },
  {
    name: 'Venus',
    radius: 0.5,
    orbitRadius: 7.5,
    orbitSpeed: 0.8,
    selfRotationSpeed: 0.1,
    color: 0xe8cda0,
    diameter: '12,104 km',
    distanceFromSun: '108.2 million km',
    moons: 0,
    atmosphere: 'Dense — 96% carbon dioxide with thick clouds of sulfuric acid',
    funFact: 'Venus rotates backwards — the Sun rises in the west and sets in the east.',
  },
  {
    name: 'Earth',
    radius: 0.55,
    orbitRadius: 10,
    orbitSpeed: 0.45,
    selfRotationSpeed: 1.2,
    color: 0x2e8bc0,
    diameter: '12,742 km',
    distanceFromSun: '149.6 million km',
    moons: 1,
    atmosphere: '78% nitrogen, 21% oxygen, plus traces of argon and CO₂',
    funFact: 'Earth is the only known planet in the universe with confirmed life.',
  },
  {
    name: 'Mars',
    radius: 0.35,
    orbitRadius: 14,
    orbitSpeed: 0.25,
    selfRotationSpeed: 1.1,
    color: 0xc1440e,
    diameter: '6,779 km',
    distanceFromSun: '227.9 million km',
    moons: 2,
    atmosphere: '95% CO₂ — very thin, with planet-wide dust storms in summer',
    funFact: 'Olympus Mons on Mars is the tallest volcano in the solar system at 21 km high.',
  },
  {
    name: 'Jupiter',
    radius: 1.4,
    orbitRadius: 22,
    orbitSpeed: 0.08,
    selfRotationSpeed: 2.5,
    color: 0xc88b3a,
    diameter: '139,820 km',
    distanceFromSun: '778.5 million km',
    moons: 95,
    atmosphere: 'Mainly hydrogen and helium — the bands are ammonia crystals at different altitudes',
    funFact: "Jupiter's Great Red Spot is a storm that has raged for over 350 years.",
  },
  {
    name: 'Saturn',
    radius: 1.2,
    orbitRadius: 30,
    orbitSpeed: 0.05,
    selfRotationSpeed: 2.2,
    color: 0xe4d191,
    hasRing: true,
    ringColor: 0xc2a366,
    ringInnerRadius: 1.6,
    ringOuterRadius: 2.7,
    diameter: '116,460 km',
    distanceFromSun: '1.43 billion km',
    moons: 146,
    atmosphere: 'Hydrogen and helium — least dense planet, it would float on water',
    funFact: "Saturn's rings are mostly water ice particles ranging from grains to house-sized chunks.",
  },
  {
    name: 'Uranus',
    radius: 0.8,
    orbitRadius: 38,
    orbitSpeed: 0.025,
    selfRotationSpeed: 1.4,
    color: 0x7de8e8,
    diameter: '50,724 km',
    distanceFromSun: '2.87 billion km',
    moons: 28,
    atmosphere: 'Hydrogen, helium and methane — methane absorbs red light giving it blue-green colour',
    funFact: 'Uranus rotates on its side with a 98° axial tilt, likely from an ancient giant collision.',
  },
  {
    name: 'Neptune',
    radius: 0.75,
    orbitRadius: 46,
    orbitSpeed: 0.015,
    selfRotationSpeed: 1.5,
    color: 0x3f54ba,
    diameter: '49,244 km',
    distanceFromSun: '4.49 billion km',
    moons: 16,
    atmosphere: 'Hydrogen, helium and methane — has the strongest winds in the solar system',
    funFact: 'Neptune has supersonic winds reaching 2,100 km/h — the fastest of any planet.',
  },
]
